
project_id = "mqqgfcghppkivptpjwxi"

[functions.generate-ai-design]
verify_jwt = true

[functions.initiate-phonepe-payment]
verify_jwt = true

[functions.verify-phonepe-payment]
verify_jwt = true

[functions.webhook-phonepe-payment]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false


