
project_id = "mqqgfcghppkivptpjwxi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[[functions]]
name = "generate-ai-design"
verify_jwt = true
cors = {origin = ["http://localhost:8080", "http://localhost:3000", "*"], headers = ["authorization", "x-client-info", "apikey", "content-type"], methods = ["POST", "OPTIONS"]}

[[functions]]
name = "initiate-phonepe-payment"
verify_jwt = true
cors = {origin = ["http://localhost:8080", "http://localhost:3000", "*"], headers = ["authorization", "x-client-info", "apikey", "content-type"], methods = ["POST", "OPTIONS"]}

[[functions]]
name = "verify-phonepe-payment"
verify_jwt = true
cors = {origin = ["http://localhost:8080", "http://localhost:3000", "*"], headers = ["authorization", "x-client-info", "apikey", "content-type"], methods = ["POST", "OPTIONS"]}

[[functions]]
name = "webhook-phonepe-payment"
verify_jwt = false
cors = {origin = ["*"], headers = ["authorization", "x-client-info", "apikey", "content-type", "x-verify"], methods = ["POST", "OPTIONS"]}
