// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const fallbackSupabaseUrl = 'https://placeholder.supabase.co';
const fallbackSupabaseAnonKey = 'placeholder-anon-key';

const resolvedSupabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const resolvedSupabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const hasSupabaseEnv = Boolean(resolvedSupabaseUrl && resolvedSupabaseAnonKey);

if (!hasSupabaseEnv) {
  console.warn('Missing Supabase environment variables. Falling back to placeholder values for build-time rendering.');
  console.warn('NEXT_PUBLIC_SUPABASE_URL:', resolvedSupabaseUrl);
  console.warn('NEXT_PUBLIC_SUPABASE_ANON_KEY:', resolvedSupabaseAnonKey ? 'Present' : 'Missing');
}

const supabaseUrl = resolvedSupabaseUrl ?? fallbackSupabaseUrl;
const supabaseAnonKey = resolvedSupabaseAnonKey ?? fallbackSupabaseAnonKey;

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
